import type { Metadata } from "next";
import { velaSans } from './fonts';
import "./globals.css";
import Header from "@/app/components/Header/Header";
import Values from "@/app/components/Main/Valuse/Values"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={velaSans.className}>
        <Header />
        <Values />
        {children}
      </body>
    </html>
  );
}
